#include "pch.h"
#include "catch_amalgamated.hpp"
#include "common/updater.hpp"

using namespace vcxproj::updater;
namespace fs = std::filesystem;

TEST_CASE("Updater normalizes and compares versions", "[updater]") {
    CHECK(normalize_version("v1.2.3") == "1.2.3");
    CHECK(normalize_version(" V2.0.0 ") == "2.0.0");

    CHECK(compare_versions("1.2.3", "1.2.3") == 0);
    CHECK(compare_versions("v1.2.10", "1.2.3") > 0);
    CHECK(compare_versions("0.0.0-dev", "0.1.0") < 0);
    CHECK(compare_versions("1.0", "1.0.0") == 0);
}

TEST_CASE("Updater parses release manifest assets", "[updater]") {
    std::string manifest_text = R"(
# generated by release workflow
version=1.2.3
tag=v1.2.3
asset_base_url=https://github.com/CitroenGames/sighmake/releases/latest/download
windows_x64=sighmake-windows-x64.zip
windows_x64_sha256=ABCDEF
linux_x64=sighmake-linux-x64.tar.gz
linux_x64_sha256=012345
)";

    std::string error;
    auto manifest = parse_release_manifest(manifest_text, &error);
    REQUIRE(manifest.has_value());
    CHECK(error.empty());
    CHECK(manifest->version == "1.2.3");
    CHECK(manifest->tag == "v1.2.3");
    CHECK(manifest->asset_base_url == "https://github.com/CitroenGames/sighmake/releases/latest/download");

    auto* windows_asset = find_asset(*manifest, "windows_x64");
    REQUIRE(windows_asset != nullptr);
    CHECK(windows_asset->name == "sighmake-windows-x64.zip");
    CHECK(windows_asset->sha256 == "abcdef");

    auto* missing_asset = find_asset(*manifest, "macos_arm64");
    CHECK(missing_asset == nullptr);
}

TEST_CASE("Updater rejects incomplete manifests", "[updater]") {
    std::string error;
    auto manifest = parse_release_manifest("windows_x64=sighmake-windows-x64.zip\n", &error);
    CHECK_FALSE(manifest.has_value());
    CHECK(error.find("version") != std::string::npos);
}

TEST_CASE("Updater verifies SHA-256 checksums", "[updater]") {
    fs::path path = fs::temp_directory_path() / "sighmake-updater-sha256-test.txt";
    {
        std::ofstream out(path, std::ios::binary);
        out << "abc";
    }

    std::string error;
    CHECK(verify_file_sha256(path.string(),
                             "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
                             &error));

    error.clear();
    CHECK_FALSE(verify_file_sha256(path.string(),
                                   "0000000000000000000000000000000000000000000000000000000000000000",
                                   &error));
    CHECK(error.find("mismatch") != std::string::npos);

    std::error_code ec;
    fs::remove(path, ec);
}
