export interface KeywordInfo {
    name: string;
    aliases: string[];
    validValues?: string[];
    valueType: 'string' | 'bool' | 'path' | 'paths' | 'enum' | 'files' | 'number' | 'command';
    context: ('solution' | 'project' | 'config' | 'file')[];
    documentation: string;
    supportsConfigQualifier: boolean;
}

export interface FunctionInfo {
    name: string;
    signature: string;
    documentation: string;
}

export const SECTION_TYPES: Record<string, string> = {
    'solution': 'Solution-level settings. Defines the solution name, configurations, and platforms.',
    'project': 'Project definition. Contains source files, compiler settings, linker settings, and dependencies for a single build target.',
    'config': 'Configuration-specific settings. Overrides project settings for a specific configuration and/or platform combination. Supports template inheritance with `: Template:Name`.',
    'file': 'Per-file settings. Overrides compiler settings for a specific source file.',
};

export const PLATFORM_CONDITIONS: Record<string, string> = {
    'windows': 'Matches all Windows platforms (Win32, x64, ARM, ARM64).',
    'linux': 'Matches the Linux platform.',
    'osx': 'Matches macOS/Darwin platforms.',
    'macos': 'Matches macOS/Darwin platforms.',
    'darwin': 'Matches macOS/Darwin platforms.',
    'win32': 'Matches the 32-bit x86 Windows platform only.',
    'x64': 'Matches the 64-bit x86-64 platform only.',
    'Win32': 'Matches the 32-bit x86 Windows platform only.',
};

export const VISIBILITY_KEYWORDS: Record<string, string> = {
    'PUBLIC': 'Headers and libraries propagate to this target AND all dependent targets (transitive).',
    'PRIVATE': 'Headers and libraries are used by this target only, not propagated to dependents.',
    'INTERFACE': 'Headers and libraries propagate to dependent targets only, not added to this target itself.',
};

export const KEYWORDS: KeywordInfo[] = [
    // ===== Solution settings =====
    {
        name: 'name',
        aliases: [],
        valueType: 'string',
        context: ['solution', 'project'],
        documentation: 'The name of the solution or project. For solutions, determines the `.sln` filename.',
        supportsConfigQualifier: false,
    },
    {
        name: 'configurations',
        aliases: ['configs'],
        valueType: 'string',
        context: ['solution'],
        documentation: 'Comma-separated list of build configurations (e.g., `Debug, Release`).',
        supportsConfigQualifier: false,
    },
    {
        name: 'platforms',
        aliases: [],
        valueType: 'string',
        context: ['solution'],
        documentation: 'Comma-separated list of target platforms (e.g., `Win32, x64`).',
        supportsConfigQualifier: false,
    },
    {
        name: 'include',
        aliases: [],
        valueType: 'path',
        context: ['solution', 'project'],
        documentation: 'Include another buildscript file. Paths are resolved relative to the current file.',
        supportsConfigQualifier: false,
    },

    // ===== Project type & identity =====
    {
        name: 'type',
        aliases: [],
        validValues: ['exe', 'app', 'application', 'lib', 'static', 'staticlib', 'dll', 'shared', 'dynamiclib', 'interface', 'header-only', 'Utility'],
        valueType: 'enum',
        context: ['project'],
        documentation: 'Project output type.\n- `exe`/`app`/`application` — Executable\n- `lib`/`static`/`staticlib` — Static library\n- `dll`/`shared`/`dynamiclib` — Dynamic library (DLL)\n- `interface`/`header-only`/`Utility` — Header-only / utility project',
        supportsConfigQualifier: false,
    },
    {
        name: 'project_name',
        aliases: [],
        valueType: 'string',
        context: ['project'],
        documentation: 'Override the project display name in the IDE.',
        supportsConfigQualifier: false,
    },
    {
        name: 'uuid',
        aliases: ['guid'],
        valueType: 'string',
        context: ['project'],
        documentation: 'Explicit GUID for the project. If not set, one is generated automatically.',
        supportsConfigQualifier: false,
    },
    {
        name: 'root_namespace',
        aliases: [],
        valueType: 'string',
        context: ['project'],
        documentation: 'The root namespace for the project.',
        supportsConfigQualifier: false,
    },
    {
        name: 'ignore_warn_duplicated_filename',
        aliases: [],
        valueType: 'bool',
        context: ['project'],
        documentation: 'Suppress warnings about duplicated filenames across the project.',
        supportsConfigQualifier: false,
    },

    // ===== Source files =====
    {
        name: 'sources',
        aliases: ['src', 'files'],
        valueType: 'files',
        context: ['project'],
        documentation: 'C/C++ source files to compile. Supports glob patterns (`src/*.cpp`, `src/**/*.cpp`) and comma-separated lists. Platform conditions: `file.cpp [!linux]`.',
        supportsConfigQualifier: false,
    },
    {
        name: 'headers',
        aliases: ['includes_files'],
        valueType: 'files',
        context: ['project'],
        documentation: 'Header files for IDE organization. Not compiled, but included in the project for navigation. Supports glob patterns.',
        supportsConfigQualifier: false,
    },
    {
        name: 'resources',
        aliases: ['resource_files'],
        valueType: 'files',
        context: ['project'],
        documentation: 'Windows resource files (`.rc`). Supports glob patterns.',
        supportsConfigQualifier: false,
    },
    {
        name: 'masm',
        aliases: ['asm_sources', 'assembly'],
        valueType: 'files',
        context: ['project'],
        documentation: 'MASM assembly source files (`.asm`, `.masm`). Supports glob patterns and platform qualifiers.',
        supportsConfigQualifier: true,
    },

    // ===== Include directories =====
    {
        name: 'includes',
        aliases: ['include_dirs', 'additional_include_directories'],
        valueType: 'paths',
        context: ['project', 'config', 'file'],
        documentation: 'Additional include directories for the compiler. Comma-separated list of paths.',
        supportsConfigQualifier: true,
    },
    {
        name: 'public_includes',
        aliases: ['public_include_dirs'],
        valueType: 'paths',
        context: ['project'],
        documentation: 'Public include directories exposed to dependent projects (transitive).',
        supportsConfigQualifier: true,
    },
    {
        name: 'forced_includes',
        aliases: ['forced_include_files'],
        valueType: 'paths',
        context: ['project'],
        documentation: 'Files that are force-included at the beginning of every compilation unit.',
        supportsConfigQualifier: true,
    },

    // ===== Preprocessor =====
    {
        name: 'defines',
        aliases: ['preprocessor', 'preprocessor_definitions'],
        valueType: 'string',
        context: ['project', 'config', 'file'],
        documentation: 'Preprocessor definitions. Comma-separated list (e.g., `NDEBUG, _CRT_SECURE_NO_WARNINGS, VERSION=2`).',
        supportsConfigQualifier: true,
    },
    {
        name: 'public_defines',
        aliases: ['public_preprocessor_definitions'],
        valueType: 'string',
        context: ['project'],
        documentation: 'Public preprocessor definitions exposed to dependent projects (transitive).',
        supportsConfigQualifier: true,
    },

    // ===== Libraries & linking =====
    {
        name: 'libs',
        aliases: ['libraries'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Libraries to link against. Comma-separated list (e.g., `user32.lib, gdi32.lib`).',
        supportsConfigQualifier: true,
    },
    {
        name: 'link_libs',
        aliases: ['additional_dependencies'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Additional library dependencies for the linker.',
        supportsConfigQualifier: true,
    },
    {
        name: 'public_libs',
        aliases: ['public_libraries'],
        valueType: 'string',
        context: ['project'],
        documentation: 'Public libraries exposed to dependent projects (transitive).',
        supportsConfigQualifier: true,
    },
    {
        name: 'libdirs',
        aliases: ['lib_dirs', 'additional_library_directories'],
        valueType: 'paths',
        context: ['project', 'config'],
        documentation: 'Additional library search directories for the linker.',
        supportsConfigQualifier: true,
    },
    {
        name: 'depends',
        aliases: ['dependencies', 'project_references'],
        valueType: 'string',
        context: ['project'],
        documentation: 'Project dependencies. Comma-separated list of project names that must be built first.',
        supportsConfigQualifier: false,
    },
    {
        name: 'ignore_libs',
        aliases: ['ignore_specific_default_libraries'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Default libraries to ignore during linking.',
        supportsConfigQualifier: true,
    },

    // ===== Output directories =====
    {
        name: 'outdir',
        aliases: ['output_dir'],
        valueType: 'path',
        context: ['project', 'config'],
        documentation: 'Output directory for the final binary.',
        supportsConfigQualifier: true,
    },
    {
        name: 'intdir',
        aliases: ['intermediate_dir'],
        valueType: 'path',
        context: ['project', 'config'],
        documentation: 'Intermediate directory for object files.',
        supportsConfigQualifier: true,
    },

    // ===== C/C++ standard & language =====
    {
        name: 'std',
        aliases: ['cpp_standard', 'language_standard'],
        validValues: ['14', '17', '20', '23'],
        valueType: 'enum',
        context: ['project', 'config'],
        documentation: 'C++ language standard version.',
        supportsConfigQualifier: true,
    },
    {
        name: 'language',
        aliases: ['lang'],
        validValues: ['C', 'C++'],
        valueType: 'enum',
        context: ['project'],
        documentation: 'The primary language of the project. Affects source file detection.',
        supportsConfigQualifier: false,
    },
    {
        name: 'c_standard',
        aliases: ['cstd'],
        validValues: ['89', '99', '11', '17', '23'],
        valueType: 'enum',
        context: ['project', 'config'],
        documentation: 'C language standard version (for C projects).',
        supportsConfigQualifier: true,
    },

    // ===== Compiler settings =====
    {
        name: 'warning_level',
        aliases: [],
        validValues: ['Level0', 'Level1', 'Level2', 'Level3', 'Level4'],
        valueType: 'enum',
        context: ['project', 'config'],
        documentation: 'MSVC warning level (/W0 through /W4). `Level3` is recommended. `Level4` enables additional warnings.',
        supportsConfigQualifier: true,
    },
    {
        name: 'optimization',
        aliases: [],
        validValues: ['Disabled', 'MinSize', 'MaxSpeed', 'Full'],
        valueType: 'enum',
        context: ['project', 'config'],
        documentation: 'Compiler optimization level.\n- `Disabled` — No optimization, debug (/Od)\n- `MinSize` — Optimize for size (/O1)\n- `MaxSpeed` — Optimize for speed (/O2)\n- `Full` — Full optimization (/Ox)',
        supportsConfigQualifier: true,
    },
    {
        name: 'runtime_library',
        aliases: [],
        validValues: ['MultiThreaded', 'MultiThreadedDebug', 'MultiThreadedDLL', 'MultiThreadedDebugDLL'],
        valueType: 'enum',
        context: ['project', 'config'],
        documentation: 'C/C++ runtime library.\n- `MultiThreaded` — Static CRT, release (/MT)\n- `MultiThreadedDebug` — Static CRT, debug (/MTd)\n- `MultiThreadedDLL` — Dynamic CRT, release (/MD)\n- `MultiThreadedDebugDLL` — Dynamic CRT, debug (/MDd)',
        supportsConfigQualifier: true,
    },
    {
        name: 'debug_info',
        aliases: ['debug_information_format'],
        validValues: ['None', 'ProgramDatabase', 'EditAndContinue'],
        valueType: 'enum',
        context: ['project', 'config'],
        documentation: 'Debug information format.\n- `None` — No debug info\n- `ProgramDatabase` — /Zi\n- `EditAndContinue` — /ZI (enables edit-and-continue debugging)',
        supportsConfigQualifier: true,
    },
    {
        name: 'exception_handling',
        aliases: ['exceptions'],
        validValues: ['Sync', 'Async', 'false'],
        valueType: 'enum',
        context: ['project', 'config'],
        documentation: 'C++ exception handling model.\n- `Sync` — Synchronous (/EHsc)\n- `Async` — Asynchronous (/EHa)\n- `false` — Disabled',
        supportsConfigQualifier: true,
    },
    {
        name: 'rtti',
        aliases: ['runtime_type_info'],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Enable runtime type information (RTTI). `/GR` when true, `/GR-` when false.',
        supportsConfigQualifier: true,
    },
    {
        name: 'multiprocessor',
        aliases: ['mp', 'multi_processor_compilation'],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Enable multi-processor compilation (/MP) for faster builds.',
        supportsConfigQualifier: true,
    },
    {
        name: 'utf8',
        aliases: ['utf8_source'],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Set source and execution character set to UTF-8 (/utf-8).',
        supportsConfigQualifier: true,
    },
    {
        name: 'cflags',
        aliases: ['compiler_flags', 'additional_options'],
        valueType: 'string',
        context: ['project', 'config', 'file'],
        documentation: 'Additional compiler flags passed directly to the compiler command line.',
        supportsConfigQualifier: true,
    },
    {
        name: 'simd',
        aliases: ['enhanced_instruction_set'],
        validValues: ['SSE', 'SSE2', 'AVX', 'AVX2'],
        valueType: 'enum',
        context: ['project', 'config'],
        documentation: 'Enhanced instruction set for SIMD operations.',
        supportsConfigQualifier: true,
    },
    {
        name: 'floating_point',
        aliases: ['fp_model', 'floating_point_model'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Floating-point model (e.g., `fast`, `precise`, `strict`).',
        supportsConfigQualifier: true,
    },
    {
        name: 'inline_function_expansion',
        aliases: ['inline_expansion'],
        validValues: ['Disabled', 'OnlyExplicitInline', 'AnySuitable'],
        valueType: 'enum',
        context: ['project', 'config'],
        documentation: 'Control inline function expansion.\n- `Disabled` — No inlining\n- `OnlyExplicitInline` — Only inline explicitly marked functions\n- `AnySuitable` — Inline any suitable function',
        supportsConfigQualifier: true,
    },
    {
        name: 'favor_size_or_speed',
        aliases: ['favor'],
        validValues: ['Neither', 'Size', 'Speed'],
        valueType: 'enum',
        context: ['project', 'config'],
        documentation: 'Favor code size or speed when optimizing.',
        supportsConfigQualifier: true,
    },
    {
        name: 'string_pooling',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Enable string pooling (/GF) to eliminate duplicate strings.',
        supportsConfigQualifier: true,
    },
    {
        name: 'minimal_rebuild',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Enable minimal rebuild (/Gm).',
        supportsConfigQualifier: true,
    },
    {
        name: 'basic_runtime_checks',
        aliases: ['runtime_checks'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Basic runtime checks (e.g., `EnableFastChecks`, `StackFrameRuntimeCheck`).',
        supportsConfigQualifier: true,
    },
    {
        name: 'buffer_security_check',
        aliases: ['buffer_security'],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Enable buffer security check (/GS).',
        supportsConfigQualifier: true,
    },
    {
        name: 'force_conformance_in_for_loop_scope',
        aliases: ['force_conformance'],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Force conformance in for loop scope (/Zc:forScope).',
        supportsConfigQualifier: true,
    },
    {
        name: 'function_level_linking',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Enable function-level linking (/Gy) to allow the linker to remove unreferenced functions.',
        supportsConfigQualifier: true,
    },
    {
        name: 'intrinsic_functions',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Enable intrinsic functions (/Oi) for faster runtime at the cost of larger code.',
        supportsConfigQualifier: true,
    },
    {
        name: 'compile_as',
        aliases: [],
        validValues: ['Default', 'CompileAsC', 'CompileAsCpp'],
        valueType: 'enum',
        context: ['project', 'config', 'file'],
        documentation: 'Force compilation as C or C++.\n- `Default` — Determined by file extension\n- `CompileAsC` — Compile as C (/TC)\n- `CompileAsCpp` — Compile as C++ (/TP)',
        supportsConfigQualifier: true,
    },
    {
        name: 'assembler_output',
        aliases: [],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Assembler output listing options.',
        supportsConfigQualifier: true,
    },
    {
        name: 'error_reporting',
        aliases: ['compiler_error_reporting'],
        validValues: ['None', 'Prompt', 'Queue', 'Send'],
        valueType: 'enum',
        context: ['project', 'config'],
        documentation: 'Internal compiler error reporting method.',
        supportsConfigQualifier: true,
    },
    {
        name: 'treat_wchar_t_as_builtin',
        aliases: ['treat_wchar_t_as_built_in_type'],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Treat `wchar_t` as a built-in type (/Zc:wchar_t).',
        supportsConfigQualifier: true,
    },
    {
        name: 'treat_warning_as_error',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Treat all warnings as errors (/WX).',
        supportsConfigQualifier: true,
    },
    {
        name: 'openmp',
        aliases: ['openmp_support'],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Enable OpenMP support (/openmp).',
        supportsConfigQualifier: true,
    },
    {
        name: 'disable_warnings',
        aliases: ['disable_specific_warnings'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Semicolon-separated list of warning numbers to disable (e.g., `4996;4267`).',
        supportsConfigQualifier: true,
    },
    {
        name: 'assembler_listing',
        aliases: ['assembler_listing_location'],
        valueType: 'path',
        context: ['project', 'config'],
        documentation: 'Location for assembler listing output.',
        supportsConfigQualifier: true,
    },
    {
        name: 'object_file_name',
        aliases: [],
        valueType: 'path',
        context: ['project', 'config', 'file'],
        documentation: 'Custom object file name or path for compilation output.',
        supportsConfigQualifier: true,
    },
    {
        name: 'program_database_file_name',
        aliases: ['pdb_file'],
        valueType: 'path',
        context: ['project', 'config'],
        documentation: 'Program database (PDB) filename for compiler debug info.',
        supportsConfigQualifier: true,
    },
    {
        name: 'browse_information',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Generate browse information for the IDE.',
        supportsConfigQualifier: true,
    },
    {
        name: 'browse_information_file',
        aliases: [],
        valueType: 'path',
        context: ['project', 'config'],
        documentation: 'Browse information file location.',
        supportsConfigQualifier: true,
    },
    {
        name: 'generate_xml_documentation_files',
        aliases: ['xml_docs'],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Generate XML documentation files from source comments.',
        supportsConfigQualifier: true,
    },
    {
        name: 'expand_attributed_source',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Expand attributed source code in listing.',
        supportsConfigQualifier: true,
    },

    // ===== Precompiled headers =====
    {
        name: 'pch',
        aliases: ['precompiled_header'],
        validValues: ['Use', 'Create', 'NotUsing'],
        valueType: 'enum',
        context: ['project', 'config', 'file'],
        documentation: 'Precompiled header mode.\n- `Use` — Use a precompiled header\n- `Create` — Create the precompiled header (typically on pch.cpp)\n- `NotUsing` — Do not use PCH for this file',
        supportsConfigQualifier: true,
    },
    {
        name: 'pch_header',
        aliases: ['precompiled_header_file'],
        valueType: 'path',
        context: ['project', 'config', 'file'],
        documentation: 'Path to the precompiled header file (e.g., `src/pch.h`).',
        supportsConfigQualifier: true,
    },
    {
        name: 'pch_output',
        aliases: ['precompiled_header_output_file'],
        valueType: 'path',
        context: ['project', 'config'],
        documentation: 'Output path for the compiled precompiled header (`.pch` file).',
        supportsConfigQualifier: true,
    },

    // ===== Linker settings =====
    {
        name: 'ldflags',
        aliases: ['linker_flags', 'link_options', 'link_additional_options'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Additional linker flags passed directly to the linker command line.',
        supportsConfigQualifier: true,
    },
    {
        name: 'subsystem',
        aliases: ['sub_system'],
        validValues: ['Console', 'Windows'],
        valueType: 'enum',
        context: ['project', 'config'],
        documentation: 'Linker subsystem.\n- `Console` — Console application\n- `Windows` — Windows GUI application',
        supportsConfigQualifier: true,
    },
    {
        name: 'generate_debug_info',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Generate debug info during linking.',
        supportsConfigQualifier: true,
    },
    {
        name: 'link_incremental',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Enable incremental linking.',
        supportsConfigQualifier: true,
    },
    {
        name: 'show_progress',
        aliases: ['link_show_progress'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Link progress display setting.',
        supportsConfigQualifier: true,
    },
    {
        name: 'output_file',
        aliases: ['link_output_file'],
        valueType: 'path',
        context: ['project', 'config'],
        documentation: 'Override the linker output file path.',
        supportsConfigQualifier: true,
    },
    {
        name: 'suppress_startup_banner',
        aliases: ['link_suppress_startup_banner'],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Suppress the linker startup banner.',
        supportsConfigQualifier: true,
    },
    {
        name: 'program_database_file',
        aliases: ['link_pdb_file'],
        valueType: 'path',
        context: ['project', 'config'],
        documentation: 'Linker PDB output file path.',
        supportsConfigQualifier: true,
    },
    {
        name: 'base_address',
        aliases: [],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Set the base address for the output binary.',
        supportsConfigQualifier: true,
    },
    {
        name: 'target_machine',
        aliases: [],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Target machine architecture for the linker.',
        supportsConfigQualifier: true,
    },
    {
        name: 'link_error_reporting',
        aliases: [],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Internal linker error reporting method.',
        supportsConfigQualifier: true,
    },
    {
        name: 'image_has_safe_exception_handlers',
        aliases: ['safe_seh'],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Image has safe exception handlers (SafeSEH).',
        supportsConfigQualifier: true,
    },
    {
        name: 'entry_point',
        aliases: ['entry_point_symbol'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Set the entry point symbol for the executable.',
        supportsConfigQualifier: true,
    },
    {
        name: 'version',
        aliases: ['link_version'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Version number embedded in the output binary header.',
        supportsConfigQualifier: true,
    },
    {
        name: 'link_program_database_file',
        aliases: ['link_pdb'],
        valueType: 'path',
        context: ['project', 'config'],
        documentation: 'Linker program database file path.',
        supportsConfigQualifier: true,
    },
    {
        name: 'generate_map_file',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Generate a map file during linking.',
        supportsConfigQualifier: true,
    },
    {
        name: 'map_file_name',
        aliases: [],
        valueType: 'path',
        context: ['project', 'config'],
        documentation: 'Path for the generated map file.',
        supportsConfigQualifier: true,
    },
    {
        name: 'fixed_base_address',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Use a fixed base address for the binary.',
        supportsConfigQualifier: true,
    },
    {
        name: 'large_address_aware',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Enable large address awareness (>2GB address space on 32-bit).',
        supportsConfigQualifier: true,
    },
    {
        name: 'optimize_references',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Remove unreferenced data and functions (/OPT:REF).',
        supportsConfigQualifier: true,
    },
    {
        name: 'enable_comdat_folding',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Enable COMDAT folding to reduce binary size (/OPT:ICF).',
        supportsConfigQualifier: true,
    },
    {
        name: 'whole_program_optimization',
        aliases: ['wpo', 'ltcg'],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Enable whole-program optimization / link-time code generation.',
        supportsConfigQualifier: true,
    },

    // ===== Librarian (static lib) settings =====
    {
        name: 'lib_output_file',
        aliases: [],
        valueType: 'path',
        context: ['project', 'config'],
        documentation: 'Output file path for the static library.',
        supportsConfigQualifier: true,
    },
    {
        name: 'lib_suppress_startup_banner',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Suppress the librarian startup banner.',
        supportsConfigQualifier: true,
    },
    {
        name: 'lib_use_unicode_response_files',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Use Unicode response files for the librarian.',
        supportsConfigQualifier: true,
    },
    {
        name: 'libflags',
        aliases: ['lib_options', 'lib_additional_options'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Additional librarian options.',
        supportsConfigQualifier: true,
    },
    {
        name: 'lib_additional_dependencies',
        aliases: ['lib_deps'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Additional dependencies for the static librarian.',
        supportsConfigQualifier: true,
    },

    // ===== Resource compiler =====
    {
        name: 'rc_culture',
        aliases: ['resource_culture'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Resource compiler culture/locale setting.',
        supportsConfigQualifier: true,
    },
    {
        name: 'rc_defines',
        aliases: ['rc_preprocessor', 'resource_defines', 'resource_preprocessor_definitions'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Preprocessor definitions for the resource compiler.',
        supportsConfigQualifier: true,
    },
    {
        name: 'rc_includes',
        aliases: ['resource_includes', 'resource_additional_include_directories'],
        valueType: 'paths',
        context: ['project', 'config'],
        documentation: 'Additional include directories for the resource compiler.',
        supportsConfigQualifier: true,
    },

    // ===== Build events =====
    {
        name: 'prebuild',
        aliases: ['pre_build_event'],
        valueType: 'command',
        context: ['project', 'config'],
        documentation: 'Command to run before the build starts.',
        supportsConfigQualifier: true,
    },
    {
        name: 'prelink',
        aliases: ['pre_link_event'],
        valueType: 'command',
        context: ['project', 'config'],
        documentation: 'Command to run after compilation but before linking.',
        supportsConfigQualifier: true,
    },
    {
        name: 'postbuild',
        aliases: ['post_build_event'],
        valueType: 'command',
        context: ['project', 'config'],
        documentation: 'Command to run after the build completes.',
        supportsConfigQualifier: true,
    },
    {
        name: 'prebuild_message',
        aliases: ['pre_build_event_message'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Message displayed before the pre-build event runs.',
        supportsConfigQualifier: true,
    },
    {
        name: 'prelink_message',
        aliases: ['pre_link_event_message'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Message displayed before the pre-link event runs.',
        supportsConfigQualifier: true,
    },
    {
        name: 'postbuild_message',
        aliases: ['post_build_event_message'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Message displayed before the post-build event runs.',
        supportsConfigQualifier: true,
    },
    {
        name: 'prebuild_use_in_build',
        aliases: ['pre_build_event_use_in_build'],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Whether the pre-build event is used in the build.',
        supportsConfigQualifier: true,
    },
    {
        name: 'prelink_use_in_build',
        aliases: ['pre_link_event_use_in_build'],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Whether the pre-link event is used in the build.',
        supportsConfigQualifier: true,
    },
    {
        name: 'postbuild_use_in_build',
        aliases: ['post_build_event_use_in_build'],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Whether the post-build event is used in the build.',
        supportsConfigQualifier: true,
    },

    // ===== Toolset & platform =====
    {
        name: 'toolset',
        aliases: ['platform_toolset'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Visual Studio platform toolset (e.g., `v143`, `v142`, `v141`).',
        supportsConfigQualifier: true,
    },
    {
        name: 'windows_sdk',
        aliases: ['windows_sdk_version', 'windows_target_platform_version'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Windows SDK version (e.g., `10.0.22621.0`).',
        supportsConfigQualifier: true,
    },
    {
        name: 'charset',
        aliases: ['character_set'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Character set for the project (e.g., `Unicode`, `MultiByte`).',
        supportsConfigQualifier: true,
    },

    // ===== Project target =====
    {
        name: 'target_name',
        aliases: ['targetname'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Override the output binary name (without extension).',
        supportsConfigQualifier: true,
    },
    {
        name: 'target_ext',
        aliases: ['targetext', 'target_extension'],
        valueType: 'string',
        context: ['project', 'config'],
        documentation: 'Override the output file extension (e.g., `.exe`, `.dll`).',
        supportsConfigQualifier: true,
    },

    // ===== Miscellaneous =====
    {
        name: 'executable_path',
        aliases: [],
        valueType: 'paths',
        context: ['project', 'config'],
        documentation: 'Additional executable search paths.',
        supportsConfigQualifier: true,
    },
    {
        name: 'generate_manifest',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Generate a manifest file for the output binary.',
        supportsConfigQualifier: true,
    },
    {
        name: 'import_library',
        aliases: [],
        valueType: 'path',
        context: ['project', 'config'],
        documentation: 'Import library path for DLL projects.',
        supportsConfigQualifier: true,
    },
    {
        name: 'ignore_import_library',
        aliases: [],
        valueType: 'bool',
        context: ['project', 'config'],
        documentation: 'Ignore the import library during linking.',
        supportsConfigQualifier: true,
    },

    // ===== Per-file specific =====
    {
        name: 'exclude',
        aliases: ['excluded', 'excluded_from_build'],
        valueType: 'bool',
        context: ['file'],
        documentation: 'Exclude this file from the build.',
        supportsConfigQualifier: true,
    },
    {
        name: 'custom_command',
        aliases: ['command'],
        valueType: 'command',
        context: ['file'],
        documentation: 'Custom build command for this file.',
        supportsConfigQualifier: true,
    },
    {
        name: 'custom_message',
        aliases: ['message'],
        valueType: 'string',
        context: ['file'],
        documentation: 'Message displayed when running the custom build command.',
        supportsConfigQualifier: true,
    },
    {
        name: 'custom_outputs',
        aliases: ['outputs'],
        valueType: 'string',
        context: ['file'],
        documentation: 'Output files produced by the custom build command.',
        supportsConfigQualifier: true,
    },
    {
        name: 'custom_inputs',
        aliases: ['inputs', 'additional_inputs'],
        valueType: 'string',
        context: ['file'],
        documentation: 'Additional input dependencies for the custom build command.',
        supportsConfigQualifier: true,
    },
];

export const FUNCTIONS: FunctionInfo[] = [
    {
        name: 'find_package',
        signature: 'find_package(PackageName, REQUIRED)',
        documentation: 'Find and configure an external package. Sets `${PackageName_INCLUDE_DIRS}` and `${PackageName_LIBRARIES}` variables.\n\nSupported packages: `Vulkan`, `OpenGL`, `SDL2`, `SDL3`, `DirectX9`, `DirectX10`, `DirectX11`, `DirectX12`.\n\n`REQUIRED` causes an error if the package is not found.',
    },
    {
        name: 'target_link_libraries',
        signature: 'target_link_libraries(\\n    LibName PUBLIC|PRIVATE|INTERFACE\\n)',
        documentation: 'Declare project dependencies with CMake-style visibility.\n- `PUBLIC` — Headers and libs propagate to dependents\n- `PRIVATE` — Used by this target only\n- `INTERFACE` — Propagates to dependents, not added to this target',
    },
    {
        name: 'uses_pch',
        signature: 'uses_pch("header.h")',
        documentation: 'Automatically configure precompiled headers. Sets up PCH usage for all source files and creates the PCH compilation step.',
    },
    {
        name: 'file_properties',
        signature: 'file_properties(file1.cpp, file2.cpp) {\\n    key = value\\n}',
        documentation: 'Apply compiler settings to multiple files at once. The brace block contains key-value pairs applied to all listed files.',
    },
    {
        name: 'set_file_properties',
        signature: 'set_file_properties(file.cpp, key = value)',
        documentation: 'Set a property on a specific file. Inline alternative to the `[file:path]` section.',
    },
    {
        name: 'folder',
        signature: 'folder("FolderName") {\\n    [project:...]\\n    ...\\n}',
        documentation: 'Organize projects into a Visual Studio solution folder. Projects defined inside the block are placed in the named folder.',
    },
];
